[project]
name = "sudoku_solver"
version = "0.1.0"
description = "Solver to solve the daily sudoku"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fake-useragent>=2.2.0",
    "playwright>=1.55.0",
]
